### ISSUE TITLE
Plugin does not open parquet files on Mac M1

### ISSUE THREAD

**Issue by akelsch** [dvirtz/vscode-parquet-viewer#83] opened 2023-07-28 15:25 UTC
Hi @dvirtz,

~~our team has encountered an issue with vscode-parquet-viewer after we have migrated our Apache Spark platform from Azure HDInsight to Azure Databricks.~~ Turns out we cannot open parquet files with your plugin anymore. The tab in VSCode will be loading forever.

I did attach a sample file to this issue. Its contents look like this (converted using a different plugin):

```json
{
  "hello": "abc",
  "world": "123"
}
```

I would be really grateful if you could fix this issue as your plugin was the go-to choice to work with parquet files in our team.

Thanks!

Edit: Looks like this is unrelated to Databricks, similar to #81 but only happening on Mac M1

[part-00000-tid-8369997251915174921-9ae69399-852b-4480-8335-60e65202bcc8-36-1-c000.snappy.parquet.zip](https://github.com/dvirtz/vscode-parquet-viewer/files/12195917/part-00000-tid-8369997251915174921-9ae69399-852b-4480-8335-60e65202bcc8-36-1-c000.snappy.parquet.zip)

**Comment by rafaelmarino** [comment] 2023-07-28 18:17
I've been having issues with the extension since yesterday also. The issue is the same for me as in other reports: "the file takes forever to load". I don't know if it eventually loads or not, since I just close it if it doesn't load in a few seconds.

I'm using pandas to check out my files as a workaround, but this extension is very much missed :)

@akelsch, does it make sense to specify how to write your parquet files? I would have thought once they are `.parquet`, how you wrote them is of no relevance.

I'm developing on:
* M1 pro 13.4.1
* VSCode 1.80.2

Thanks @dvirtz for your work on this great extension.

**Comment by akelsch** [comment] 2023-07-28 21:48
Oh, so the issue is not caused by Databricks but rather appeared at the same time as our migration (what a coincidence).

I am also on Mac M1 and downgrading the plugin version to 2.2.2 does actually let me open above parquet file. 2.3.0 seems to be the first breaking version for me with 2.3.2 not working too.

Looks like some form of regression on Mac M1 only though because it is working on my Windows machine.

**Comment by rafaelmarino** [comment] 2023-07-28 23:22
Nice find. Exactly the same behavior I'm experiencing: 2.2.2 is the last working version. 

Is this `arrow` not playing nice with M1 chips perhaps?

PS: Anecdotal but perhaps useful, this week in a python project I couldn't install arrow8.0 in a python3.7 venv (`ERROR: Failed building wheel for pyarrow`), so it looks like arrow-m1 are not that compatible out of the box.

**Comment by space7panda** [comment] 2023-07-29 21:25
Also having similar issues:

```
2023-07-30 00:20:05.383 [info] Extension host with pid 34973 started
2023-07-30 00:20:05.428 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-07-30 00:20:05.432 [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense, startup: true, activationEvent: '*'
2023-07-30 00:20:05.476 [info] ExtensionService#_doActivateExtension formulahendry.auto-rename-tag, startup: true, activationEvent: '*'
2023-07-30 00:20:05.483 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2023-07-30 00:20:05.498 [info] ExtensionService#_doActivateExtension nhoizey.gremlins, startup: true, activationEvent: '*'
2023-07-30 00:20:05.596 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-07-30 00:20:05.608 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-07-30 00:20:05.618 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-07-30 00:20:05.668 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-07-30 00:20:05.777 [info] Eager extensions activated
2023-07-30 00:20:05.779 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.780 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.784 [info] ExtensionService#_doActivateExtension aaron-bond.better-comments, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.789 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.795 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.817 [info] ExtensionService#_doActivateExtension formulahendry.code-runner, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:05.869 [info] ExtensionService#_doActivateExtension GitHub.copilot, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.084 [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.128 [info] ExtensionService#_doActivateExtension usernamehw.errorlens, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.133 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.139 [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.162 [info] ExtensionService#_doActivateExtension withfig.fig, startup: false, activationEvent: 'onStartupFinished'
2023-07-30 00:20:06.618 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-07-30 00:20:06.631 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-07-30 00:20:06.644 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-07-30 00:20:24.865 [info] ExtensionService#_doActivateExtension dvirtz.parquet-viewer, startup: false, activationEvent: 'onCustomEditor:parquetViewer.parquetViewer'
2023-07-30 00:20:25.037 [error] Activating extension dvirtz.parquet-viewer failed due to an error:
2023-07-30 00:20:25.037 [error] Error: Failed to find binding for arrow-parquet-reader
    at loadBinding (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/node_modules/pkg-prebuilds/bindings.js:95:27)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/node_modules/parquet-reader/dist/index.js:34:51)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/dist/src/arrow-backend.js:27:26)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/dist/src/parquet-document.js:45:25)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/dist/src/parquet-document-provider.js:40:44)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/dist/src/parquet-editor-provider.js:40:37)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/space7panda/.vscode/extensions/dvirtz.parquet-viewer-2.3.2/dist/src/extension.js:39:35)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/Users/space7panda/.vscode/extensions/github.copilot-1.99.289/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
    at i.rb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26583)
    at async Promise.all (index 0)

```

**Comment by space7panda** [comment] 2023-07-29 21:56
> Also having similar issues:
> 
> ```
> 2023-07-30 00:20:05.383 [info] Extension host with pid 34973 started
> 2023-07-30 00:20:05.428 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
> ```

was playing around with ChatGPT a bit, updated Python, Pip and installed PyArrow, doesn't seem to help with error aswell...

```bash
Python 3.11.4
pip 23.2.1
pyarrow.__version__ 12.0.1

```

**Comment by space7panda** [comment] 2023-07-29 22:17
mkay i got some slight progress,
i cloned this repo
```bash
git clone ...
brew install pipenv
npm i
npm run test
```
it kind worked for a few sec in tests, I'm gonna dig a bit more tomorrow

**Closed** 2023-07-30 17:05 UTC
