### ISSUE TITLE
No longer able to view Parquet files in VS Code

### ISSUE THREAD

**Issue by nm88** [dvirtz/vscode-parquet-viewer#112] opened 2024-01-12 18:31 UTC
This extension was working previously (1month ago), however, now unable to view Parquet files in JSON format.

Plugin/Extension v2.6.2 installed
VS Code Version: 1.43.0
Mac OS Ventura 13.4

<img width="1792" alt="Screenshot 2024-01-12 at 6 26 50 pm" src="https://github.com/dvirtz/vscode-parquet-viewer/assets/16080156/57daeeb3-7c48-4eb4-aa8a-bcf32879177b">
<img width="1790" alt="Screenshot 2024-01-12 at 6 27 07 pm" src="https://github.com/dvirtz/vscode-parquet-viewer/assets/16080156/2af0e32a-aa31-4068-a933-31eebd907db9">
<img width="1791" alt="Screenshot 2024-01-12 at 6 27 17 pm" src="https://github.com/dvirtz/vscode-parquet-viewer/assets/16080156/c039860c-8bfc-4cc7-99a5-040250867441">

**Comment by dvirtz** [comment] 2024-01-13 20:08
As you can see in https://github.com/dvirtz/vscode-parquet-viewer/blob/master/package.json#L27 the minimum VSCode version this extension supports is 1.63.0 and this hasn't changed lately. 
I'm not sure how it worked for you until now.

**Comment by at672** [comment] 2024-01-18 22:07
I have a possibly related issue. I too cannot view parquets in VSCode with the extension installed. I have a function I've created that's doing the following (Python 3.9 code)

`def save_df_as_parquet( df, fname ):
    half_floats = df.select_dtypes(include="float16")
    df[half_floats.columns] = half_floats.astype("float32")
    df.to_parquet( save_dir + fname + ".parquet", engine = 'pyarrow')
    #Is this needed? VSCodekeeps trying to open the parquet
    return 0

_ = save_df_as_parquet(y1_test_pred_df, fname = "y1_test_pred_df")
`

I've tried many different versions of this, one where I don't return anything and don't save the function output to a value, but no matter what I try, every time this code runs, the parquet viewer extension pops up in the bottom right and says it's trying to open the file. I'm not interested in opening the file, I'm simply interested in writing a parquet file. For now I've disabled the extension.

**Comment by dvirtz** [comment] 2024-01-21 09:53
@at672 I'm not sure how this is related to the OP. Do you also use VSCode 1.43.0?
Is the problem that VSCode can't open the parquet file or that it tries to open it in the first place?

**Comment by at672** [comment] 2024-01-21 23:19
I'm using VS Code version 1.85.2 on Windows 10. I'm assuming the extension should work for this version too?

The problem is both. It is trying to open the file when I have not asked for the file to be open, and when it tries to open it the file, it stalls. The notification in the bottom right hand corner will appear and last for up to a minute.

It should be noted this is for a large file (4GB on disk). So it could be an issue that some large files can't be opened. My system has enough memory (32GB) to be able to view it. I think it would be nice, if possible, to have it where not all of the data is loaded in memory at once, and is instead buffered.

**Comment by dvirtz** [comment] 2024-01-22 13:04
Thanks for the info @at672. The problem with extra large files is known. The problem is that VSCode doesn't have a built in support for buffered document view, as far as I'm aware, and implementing that as a WebView is quiet a lot of work.
If you could create a minimal reproducible example of the unrequested file open that would be great. I couldn't reproduce it myself.

**Comment by at672** [comment] 2024-01-24 20:16
What specifically are you saying? Are you saying I should test the same exact procedure, except on a much smaller file size (e.g. 30 MB instead of 4 GB), or are you saying you'd like me to upload something for you? I can do both, and I'll probably try the former since you've suggested it. As far as file uploads go, I'm not sure where the proper place is to do that on a thread like this.

**Comment by dvirtz** [comment] 2024-01-24 23:07
I've created issue https://github.com/dvirtz/vscode-parquet-viewer/issues/114 to discuss parquet files being opened unintentionally.
Closing this issue for now as it seems unrelated.

**Closed by dvirtz** 2024-01-24 23:07 UTC
