### ISSUE TITLE
Error: invalid parquet version

### ISSUE THREAD

**Issue by tomers** [dvirtz/vscode-parquet-viewer#65] opened 2022-12-08 15:00 UTC
I get an error trying to open a Parquet file in VS code:

> Error: while reading /home/tshalev/dev/squidward/build/isolation_errors/isolation_errors.parquet: Error: invalid parquet version
```

File info:

❯ parquet-tools inspect foo.parquet

############ file meta data ############
created_by: parquet-cpp-arrow version 10.0.1
```
Any help would be appreciated :pray:

**Comment by tomers** [comment] 2022-12-08 15:06
I got the same error when trying to use another extension, `Parquet File Viewer`.

**Comment by dvirtz** [comment] 2022-12-10 18:27
Duplicate of https://github.com/dvirtz/vscode-parquet-viewer/issues/55

**Closed by dvirtz** 2022-12-10 18:27 UTC

**Comment by tomers** [comment] 2022-12-10 21:46
#55 was closed as stale, so there's no real solution to this problem
(provided one cannot control the input Parquet file).

**Comment by dvirtz** [comment] 2022-12-10 23:32
It's a backend bug: https://github.com/dvirtz/parquets/issues/18

Unfortunately, it doesn't seem like there's any javascript/typescript library with good Parquet support, and I don't have enough knowledge to implement the missing functionality.
